sudo: false

language: java
jdk: oraclejdk8

after_success:
- sh push_release.sh

deploy:
  provider: releases
  api_key:
    secure: RJDjJzWPneaP0coZ7I6S8q/CMuCfyf7dNRwh6h27y4NUWic5qIMQkqPo/0vI75C/aLx/XSX9O7fdX/5BtLS/RmpUq4mmFPM+UMy5ed0wjNQCDat16oPxiK+C5AgdB9CWV90edYn+w3t+TyWSqlopmTxU/LvTwbtyDQyhIXDbWo52uPknPmSrgbzDcGWv7pDvvHSPci6qZPA+feqBkOsH60HwKTYaavOpRceYM4v7FHds8y8ySXx7kCus33ktZChMKwsTnP46+D41QQkmYLFgtTbyTmwQw+ge0XNBwbtC55YKJciN1MvWGLTsbPMxLpp9hgt03xKC0CCsILq88UBsLuVEc2uTVrT1tDO5f0XknUN4l5ZSSxBhh4kXYHGj35n99WOmH4gikLet6OCEzR9BZuJAukPdUSndvFnQKLVI0lpSikjNybjB0rhvIqEHPJrxMW8mlFC1W7mgxcf9CE8lMX8w22zVFeA7QKftODo/dpJFip20NGnaD90HHy4aZNE+ao/nGVgbWuee58wQ8uiI5N66hxPxPBZImSY6GP9xercQp5nJA34B4ahpVpQZYsfw0/GRA0hQNiFVRq0DOvYAn6OmEfwKeq2PzlELO0SD+giBkkxb4bTYG0PXpGMyK3AGeX+4lMcWm/BRg2AeHDy2HxseWhN87m1VfzeP2wrirBY=
  file: target/AdvancedKitsReloaded.jar
  on:
    repo: TryHardDood/AdvancedKitsReloaded

script: mvn clean package
