name: ${project.name}
main: hu.tryharddood.advancedkits.AdvancedKits
version: ${project.version}
author: TryHardDood
website: ${project.url}
softdepend: [Vault]
commands:
  kit:
    aliases: [akits, akit, kits]
    description: Main kit command.
    usage: /kit
  mbchat:
    aliases: []