name: AdvancedKitsReloaded
main: hu.tryharddood.advancedkits.AdvancedKits
version: 3.0.28-STABLE
author: TryHardDood
website: https://tryharddood.github.com/web
softdepend: [Vault]
commands:
  kit:
    aliases: [akits, akit, kits]
    description: Main kit command.
    usage: /kit
  mbchat:
    aliases: []